export const PORTFOLIO_DETAILS_REQUEST = 'PORTFOLIO_DETAILS_REQUEST';
export const PORTFOLIO_DETAILS_SUCCESS = 'PORTFOLIO_DETAILS_SUCCESS';
export const PORTFOLIO_DETAILS_FAILS = 'PORTFOLIO_DETAILS_FAILS';